[package]
name = "picky-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
picky = "6.3.0"
interoptopus = "0.13.12"

[dev-dependencies]
interoptopus_backend_csharp = "0.13.13"
